---
title: "SimpleSystemSummary"
author: "WataruFujishige"
date: "2017年12月31日"
output: html_document
---

```{r setup, include=FALSE}
library(WinPerfCounter)
library(ggplot2)
data <- WinPerfCounter.readcsv("tests/testthat/test.csv")
summary <- WinPerfCounter.miniSummary(data)
knitr::opts_chunk$set(echo = TRUE, fig.width=12, fig.height=8)
```

## Summary

```{r echo=FALSE, warning=FALSE, asis=TRUE}
library(knitr)
s <- max(data$Timestamp) - min(data$Timestamp)
paste("Duration: ", s, units(s))
paste("DataPoints: ", length(data))
```

## Total

### CPU

```{r, echo=FALSE, warning=FALSE}
d <- WinPerfCounter.Metric.CPU(data)
g <- ggplot(d, aes(x=Timestamp, y=value))
g + ylab("Processor Usage[%]") + geom_point() + ylim(0.0, 100.0)
```

### Memory

Total

```{r, echo=FALSE, warning=FALSE}
memory <- WinPerfCounter.Metric.Memory(data)
g <- ggplot(memory, aes(x = Timestamp, y=valueInGB))
g + geom_point(aes(colour = metric)) + ylim(0, 16)
```

## Process(Explorer)

### CPU

```{r, echo=FALSE, warning=FALSE}
cpu <- WinPerfCounter.Process.Metric.CPU(data, "explorer")
g <- ggplot(cpu, aes(x = Timestamp, y=value))
g + geom_point(aes(colour = metric)) + ylim(0, 100.0)
```

### Memory

```{r, echo=FALSE, warning=FALSE}
memory <- WinPerfCounter.Process.Metric.Memory(data, "explorer")
g <- ggplot(memory, aes(x = Timestamp, y=valueInGB))
g + geom_point(aes(colour = metric)) + ylim(0, 1)
```

## Process (OneDrive)

### CPU

```{r, echo=FALSE, warning=FALSE}
cpu <- WinPerfCounter.Process.Metric.CPU(data, "OneDrive")
g <- ggplot(cpu, aes(x = Timestamp, y=value))
g + geom_point(aes(colour = metric)) + ylim(0, 100.0)
```

### Memory

```{r, echo=FALSE, warning=FALSE}
memory <- WinPerfCounter.Process.Metric.Memory(data, "OneDrive")
g <- ggplot(memory, aes(x = Timestamp, y=valueInGB))
g + geom_point(aes(colour = metric)) + ylim(0, 1)
```


